require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: <%= RUBY_VERSION[/\d+\.\d+/] %>
  Exclude:
    - "bin/*"
    - db/schema.rb
    - "tmp/**/*"
    - "vendor/**/*"

Layout/HashAlignment:
  EnforcedColonStyle:
    - table
    - key
  EnforcedHashRocketStyle:
    - table
    - key

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Exclude:
    - "config/**/*"

Metrics/MethodLength:
  Max: 18
  Exclude:
    - "db/migrate/*"

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/VariableNumber:
  Enabled: false

Performance/Casecmp:
  Enabled: false